### ISSUE TITLE
Font icons missing

### ISSUE THREAD

**Issue by c00kiemon5ter** [moetunes/Some_sorta_bar#2]
The default font `"-*-terminusmod.icons-medium-r-*-*-12-*-*-*-*-*-*-*"` is not recognized, even though it is installed.  
I use `"-Misc-Terminusmodx.Icons-Medium-R-Normal--12-120-72-72-C-60-ISO8859-1"` but with the latest updates the icons are missing. 

If I reset to 706531ee7176f3e4aaa6dd1a10fe526f18d11fbd everything is good again.

Here are my config options

```
#define _XOPEN_SOURCE 600
#define TOP_BAR 0        // 0=Bar at top, 1=Bar at bottom
#define BAR_HEIGHT 16
#define BAR_WIDTH 0      // 0=Full width or num pixels
#define BAR_CENTER 0     // 0=Screen center or pos/neg to move right/left
//#define FONT "-*-terminusmod.icons-medium-r-*-*-12-*-*-*-*-*-*-*"
#define FONT "-Misc-Terminusmodx.Icons-Medium-R-Normal--12-120-72-72-C-60-ISO8859-1"
#define FONTS_ERROR 1      // 0 to have missing fonts error shown
```

**Comment by c00kiemon5ter** [comment]
I have some songs whose titles are greek, but with wrong encoding, 
so the titles show up as icons in the bar with the above font. 
That causes the end of the line to show some random chars. 

Also, it seems redrawing needs some work. There seems to be a lot more flickering than before, and
if a big title gets replaced by a smaller one, chars from the old title can be seen (threy are not cleared).

**Comment by moetunes** [comment]
I get the font syntax I use from xfontselect, the default font works here as listed, can you check if you need different syntax for that font?
If you want the icons from fonts shown now you just copy/paste them into the text like with dzen.
I copied some greek letters from the net into my text and had them showing by adding plain terminus font to the start of the font list, as the first font in the list is used first.
#define FONT "-_-terminus-medium-r-_-_-12-_-_-_-_-_-_-_,-_-terminusmodx.icons-medium-r-_-_-12-_-_-_-_-_-_-_,-_-stlarch-medium-_-_-_-10-_-_-_-_-_-_-*"
If you open terminus and terminusmodx in xfd side by side you can see terminusmodx has it's icons where the greek letters are in terminus. That might be why stlarch made the stlarch font.
I've added 'double buffering' so it should be flicker free now.

**Comment by c00kiemon5ter** [comment]
alright, flickering is fixed ;) 
also, I got the "icon" letters back by using the letter _directly_, and not the unicode
that is, for example, using `ë` and not `\uEB`. it works that way, so it's good. 

about the default font, `xfontsel` says that `terminusmod.icons` isn't there, 
but `terminusmod,icons` is (did you see that?)

```
terminusmod.icons  # bad
           ^
terminusmod,icons  # good
           ^
```

I reinstalled and it's still that way, with a comma, and not a dot :p
