### ISSUE TITLE
expose events

### ISSUE THREAD

**Issue by c00kiemon5ter** [moetunes/Some_sorta_bar#3]
switching to a tty and back to X, or simply hovering a window over the bar, "erases" that part of the bar, 
until it reads new input data. this has happened before, so I guess it's an easy fix ;)

**Comment by moetunes** [comment]
I've added a 1/5th of a second timeout to select, I'll see if there's a better way as time permits.

**Comment by c00kiemon5ter** [comment]
I'm not sure if that fixes it, but in `mopag` we do this:

``` diff
diff --git a/some_sorta_bar.c b/some_sorta_bar.c
index e503fc4..cf5028f 100644
--- a/some_sorta_bar.c
+++ b/some_sorta_bar.c
@@ -282,11 +282,12 @@ int main(int argc, char ** argv){
         values.foreground = theme[i].color;
         values.line_width = 2;
         values.line_style = LineSolid;
+        values.graphics_exposures = False;
         if(font.fontset) {
-            theme[i].gc = XCreateGC(dis, root, GCBackground|GCForeground|GCLineWidth|GCLineStyle,&values);
+            theme[i].gc = XCreateGC(dis, root, GCBackground|GCForeground|GCLineWidth|GCLineStyle|GCGraphicsExposures,&values);
         } else {
             values.font = font.font->fid;
-            theme[i].gc = XCreateGC(dis, root, GCBackground|GCForeground|GCLineWidth|GCLineStyle|GCFont,&values);
+            theme[i].gc = XCreateGC(dis, root, GCBackground|GCForeground|GCLineWidth|GCLineStyle|GCFont|GCGraphicsExposures,&values);
         }
     }

```

also the created window has these attributes:

``` c
    XSetWindowAttributes wa;
    wa.background_pixel = bg;
    wa.override_redirect = 1;
    wa.event_mask = ExposureMask;
    w = XCreateWindow(dis, root,
        0, TOP ? 0 : sheight - HEIGHT, swidth, HEIGHT,
        1, CopyFromParent, InputOutput, CopyFromParent,
        CWBackPixel | CWOverrideRedirect | CWEventMask, &wa);
```

I think that's the part that ignores windows on top of the bar to "erase" the contents, and not have to redraw.

**Comment by moetunes** [comment]
I'd tried graphics exposures before but not with the background pixel set. Still didn't work here. From what I understand, and I could be wrong, for the pixels to be saved when a window is covered backing_store has to be on and that's a graphic card thing and most drivers turn it off by default.
Before I added the timeout to select, no X events were processed until there was some text input and select did it's thing. With the timeout, every fifth of a second X can do something.

**Comment by moetunes** [comment]
I had a look at the mopag code, it redraws on an expose so there's nothing special there.
I changed what select watches and now when the bar is covered and uncovered it looks like the text was never cleared.

**Comment by c00kiemon5ter** [comment]
works great, thanks ;)
