### ISSUE TITLE
&R is not aligning to the right.

### ISSUE THREAD

**Issue by DwarfJockey** [moetunes/Some_sorta_bar#4]
Using &R does not align the text to the right, in fact eveything after &R is not printed at all. &C works correctly though.

**Comment by moetunes** [comment]
Works ok here [url=http://ompldr.org/vZTltcw][img]http://ompldr.org/tZTltcw[/img][/url]
and the conky I use :
out_to_x no
out_to_console yes
double_buffer yes
use_spacer left
update_interval 1
no_buffers yes

TEXT
&L**&4Î &6${mem}  &4±&2${execi 20 /home/pnewm/.bin/sensors_out} &4µ &2 $freq_g &3${cpu cpu1}% ${cpu cpu2}% ${cpu cpu3}% ${cpu cpu4}%** &C**&3 ****&4ð &6 $battery &4 ¤ &2${if_up wlan0}${downspeed wlan0}${wireless_link_qual_perc wlan0}%$else${downspeed eth0}$endif*\*   &R*_&4¹&3 ${uptime} &4É&2 ${time %a %d/%m} &4:&6 ${execi 60 /home/pnewm/progs/c.files/fuzzyctime} &4ê *_

It might be handy to see what you're using for the text and what you've chosen for the defines in some_sorta_bar. I've checked with different scripts and I can't have it not show what's after &R here so you might be doing something I haven't thought of yet.

**Comment by moetunes** [comment]
Ok I found that having a colour right before the right marker
e.g. &3&R
had the right text written with the centered text and nothing was shown on the right. Is that what's happening on yours?

**Comment by moetunes** [comment]
I pushed a fix, see if your original text works now please.

**Comment by c00kiemon5ter** [comment]
I've been having a similar problem, although most text after `&R` is printed the last part of the text is not. 
I use [this](https://github.com/c00kiemon5ter/scripts/blob/master/statusbar#L28) to gather info and print it, and this gets passed to some_sorta_bar. 
So, date is not shown, if I switch it with any other text, then date is shown and the other text is not.
That is, it's always the last part that's not shown.

Also, if there's a newline `\n` anywhere in the string, except the very end of it, some_sorta_bar crashes.

**Comment by DwarfJockey** [comment]
With the new fix the following occurs with entered text:

"test1 &R test2 test3"

```
test1
```

"test1 &R&2 test2 test3"

```
test1                     test2     
```

**Comment by moetunes** [comment]
If you could, with the bar width set to zero e.g.
#define BAR_WIDTH 0      // 0=Full width or use num pixels
and some_sorta_bar rebuilt run in a terminal
 while true; do printf "test1 &R test2 test3"; sleep 1; done | some_sorta_bar
Works 100% here even with colours thrown in lots of places.
The only way I can have text not shown is if I have the bar width wider than the screen so I'm having trouble finding out why you guys have the problem.
cookie I tried with most of your script and this is the result
http://ompldr.org/vZWE2MQ 
(I like the seperators :) )

**Comment by moetunes** [comment]
Ok I might have stumbled onto something. some_sorta_bar only prints one line of text, obviously, so trying to print "test3" in a new line like
 while true; do printf "test1 &4&R test2 \ntest3"; sleep 1; done |  ./progs/c.files/some_sorta_bar/some_sorta_bar
has "test3" not show up. Doesn't segfault here tho.
I never thought anyone would try to print multiline text to a one line bar so I'll have to see what I can do about that.

**Comment by c00kiemon5ter** [comment]
ha, it works there I see :)  I get this (top right corner of my screen):

![date_missing](http://i.imgur.com/ya8eK.png)

that empty space is where date should be, but it's missing
and as I said, if I switch date with volume, then date is ok, but volume is missing :P
I will see what I can come up with, setting WIDTH to a different value.

I repeat this, in case you missed it:

> Also, if there's a newline `\n` anywhere in the string, except the very end of it, some_sorta_bar crashes

**Comment by c00kiemon5ter** [comment]
> ```
> while true; do printf "test1 &4&R test2 \ntest3"; sleep 1; done | ./progs/c.files/some_sorta_bar/some_sorta_bar
> ```

this results in segmentation fault here and as mentioned above `\n` seems to be what's causing it. 

_Edit_: nope, it's something else, cause even without it, it still crashes 

---

Alright, here are some tests with unchanged/default config (font fallbacks to _Fixed_):

missing right (**bug**):

```
$ while true; do printf "&L%s &C%s &R%s\n" "left" "center" "right"; sleep 1; done | ./some_sorta_bar
$ # also with no new line at the end
$ while true; do printf "&L%s &C%s &R%s" "left" "center" "right"; sleep 1; done | ./some_sorta_bar
```

missing right with new line after center element (expected):

```
$ while true; do printf "&L%s &C%s\n &R%s\n" "left" "center" "right"; sleep 1; done | ./some_sorta_bar
```

missing center and right with new line after left element (expected):

```
$ while true; do printf "&L%s\n &C%s &R%s\n" "left" "center" "right"; sleep 1; done | ./some_sorta_bar
```

crashes with no center element (**bug**):

```
$ while true; do printf "&L%s &R%s\n" "left" "right"; sleep 1; done | ./some_sorta_bar
$ # same with no newline at the end
$ while true; do printf "&L%s &R%s" "left" "right"; sleep 1; done | ./some_sorta_bar
```

missing right with only center and right elements (**bug**):

```
$ while true; do printf "&C%s &R%s\n" "center" "right"; sleep 1; done | ./some_sorta_bar
```

works as expected with only left and center elements:

```
$ while true; do printf "&L%s &C%s\n" "left" "center"; sleep 1; done | ./some_sorta_bar
```

---

:zap: So it seems there is a bug with `&R` here.

---

Will now try to change `WIDTH`.

_Update_: No changes, the bar is smaller, but right is still missing, and the behavior is the same as the above tests.

**Comment by moetunes** [comment]
If there's no new line before a &R i have text shown on the right every time so I don't think it is that but more to do with width. I think the problem might come from the code in print_text(), can you comment out

```
if((k+wsize) > width) {
    k = width;
    return;
}
```

rebuild and see if there's text on the right with maybe the last bit missing?

**Comment by DwarfJockey** [comment]
Commenting out the portion of print_text() works except for the last character only being half drawn on the screen.

**Comment by c00kiemon5ter** [comment]
Yeah, commenting out that part, seems to work :) 
all of the above test with missing right, now pass

but this still stands:

> crashes with no center element (**bug**):
> 
> ``` bash
> $ while true; do printf "&L%s &R%s\n" "left" "right"; sleep 1; done | ./some_sorta_bar
> $ # same with no newline at the end
> $ while true; do printf "&L%s &R%s" "left" "right"; sleep 1; done | ./some_sorta_bar
> ```

**Comment by moetunes** [comment]
I've pushed what I believe is a fix for the right text not showing. Please test it and let me know.
cookie I don't know why it fails for you with no centered text. redhalo do you have that issue?
It's not necessary anymore to have text marked for left alignment, it starts there by default so &L can be left out if you like.

**Comment by c00kiemon5ter** [comment]
I don't know either, but that's ok, cause I don't use `&C` anyways :) 

The fix works, pulled and tested. All good here.

**Comment by moetunes** [comment]
Well I'm confused, the bug was that it crashed with no center element but you're ok now 'cause you don't use &C? :P
If you're happy I'm happy.
I'll be trying to lower the resources some_sorta_bar uses today if everything is ok now.

**Comment by c00kiemon5ter** [comment]
haha, yeah, the bug is there for me, but I don't use `&C` so it doesn't affect me directly,
but other people might be getting, just reporting here :)

I only used `&R` with the date, and that's fixed now, so I'm happy ;)

**Comment by c00kiemon5ter** [comment]
Hmm, I think an empty `&` still causes problems. 

``` bash
$ while true; do printf "&L%s&R%s\n" "left" "right"; sleep 1; done | some_sorta_bar
```

but this only prints `r    <spaces>` on the right side, the `ight` part is hidden:

``` bash
$ while true; do printf "&L%s&R%s\n" "left" "r&ight"; sleep 1; done | some_sorta_bar
$ while true; do printf "&L%s&R%s\n" "left" "r& ight"; sleep 1; done | some_sorta_bar
```

**Comment by DwarfJockey** [comment]
Latest push works for me. I have had no issues with a missing &C.

**Comment by c00kiemon5ter** [comment]
hey @redhalo can you test if what I posted also affects you ?

> but this only prints `r    <spaces>` on the right side, the `ight` part is hidden:
> 
> ``` bash
> $ while true; do printf "&L%s&R%s\n" "left" "r&ight"; sleep 1; done | some_sorta_bar
> $ while true; do printf "&L%s&R%s\n" "left" "r& ight"; sleep 1; done | some_sorta_bar
> ```

**Comment by moetunes** [comment]
I had the same thing here cookie, I had left part of a check out of the right alignment section. Apologies for that. It should be fine with a git pull.

**Comment by c00kiemon5ter** [comment]
yep, it's good now :) thanks

**Comment by moetunes** [comment]
Since it seems to be working ok for all I'll close this now
